#!/usr/bin/env bash
rm -rdf ./android/.vs
rm -rdf ./android/bin
rm -rdf ./android/obj
rm -rdf ./ios/ExponeaSDK.iOS/.vs
rm -rdf ./ios/ExponeaSDK.iOS/bin
rm -rdf ./ios/ExponeaSDK.iOS/obj
rm -rdf ./ios/ExponeaSDK.iOS.Notifications/.vs
rm -rdf ./ios/ExponeaSDK.iOS.Notifications/bin
rm -rdf ./ios/ExponeaSDK.iOS.Notifications/obj
rm -rdf ./pcl/.vs
rm -rdf ./pcl/bin
rm -rdf ./pcl/obj
rm -rdf ./example/.vs
rm -rdf ./example/ExamplePushContentExtension/bin
rm -rdf ./example/ExamplePushContentExtension/obj
rm -rdf ./example/ExamplePushServiceExtension/bin
rm -rdf ./example/ExamplePushServiceExtension/obj
rm -rdf ./example/packages
rm -rdf ./example/XamarinExample/bin
rm -rdf ./example/XamarinExample/obj
rm -rdf ./example/XamarinExample.Android/bin
rm -rdf ./example/XamarinExample.Android/obj
rm -rdf ./example/XamarinExample.Huawei/bin
rm -rdf ./example/XamarinExample.Huawei/obj
rm -rdf ./example/XamarinExample.iOS/bin
rm -rdf ./example/XamarinExample.iOS/obj
rm -rdf ~/.nuget
